### ISSUE TITLE
Add .github/release.yaml

### ISSUE THREAD

**Issue by Coordinate-Cat** [Coordinate-Cat/watchpoint-gui#30]
```
changelog:
  exclude:
    authors:
      - github-actions
  categories:
    - title: Features
      labels:
        - enhancement
    - title: Fixes
      labels:
        - bug
    - title: Docs
      labels:
        - documentation
    - title: Refactors
      labels:
        - refactor
    - title: Upgrades
      labels:
        - dependencies
    - title: Other Changes
      labels:
        - "*"
```
